name: alchemist
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - certifi=2025.1.31=pyhd8ed1ab_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - mpi=1.0=openmpi
  - mpi4py=3.1.3=py310h6075a6b_1
  - ncurses=6.4=h6a678d5_0
  - openmpi=4.1.3=h8b79891_4
  - openssl=1.1.1w=h7f8727e_0
  - pip=25.0=py310h06a4308_0
  - python=3.10.9=h7a1cb2a_2
  - python_abi=3.10=2_cp310
  - readline=8.2=h5eee18b_0
  - setuptools=75.8.0=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py310h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.2.2
      - accelerate==1.1.1
      - addict==2.4.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.16
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anyio==4.8.0
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - av==14.3.0
      - basicsr==1.4.2
      - beautifulsoup4==4.13.4
      - charset-normalizer==3.4.1
      - click==8.1.8
      - comm==0.2.2
      - contourpy==1.3.1
      - cycler==0.12.1
      - datasets==3.5.0
      - debugpy==1.8.14
      - decorator==5.1.1
      - decord==0.6.0
      - deepspeed==0.16.6
      - diffusers==0.27.2
      - dill==0.3.8
      - docstring-parser==0.16
      - einops==0.7.0
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fastapi==0.115.6
      - ffmpeg==1.4
      - ffmpy==0.5.0
      - filelock==3.13.1
      - flash-attn==2.5.7
      - fonttools==4.55.4
      - frozenlist==1.5.0
      - fsspec==2024.2.0
      - ftfy==6.3.1
      - future==1.0.0
      - gradio==5.0.0
      - gradio-client==1.4.0
      - grpcio==1.72.0
      - h11==0.14.0
      - hjson==3.1.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.30.2
      - idna==3.10
      - imageio==2.34.0
      - imageio-ffmpeg==0.5.1
      - importlib-metadata==8.6.1
      - iniconfig==2.0.0
      - inquirerpy==0.3.4
      - ipdb==0.13.13
      - ipykernel==6.29.5
      - ipython==8.31.0
      - ipywidgets==8.1.6
      - jaxtyping==0.3.1
      - jedi==0.19.2
      - jinja2==3.1.3
      - joblib==1.4.2
      - jsonargparse==4.36.0
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.14
      - kiwisolver==1.4.8
      - kornia==0.8.0
      - kornia-rs==0.1.8
      - lazy-loader==0.4
      - lightning-utilities==0.14.3
      - lmdb==1.6.2
      - loguru==0.7.2
      - lpips==0.1.4
      - markdown==3.8
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.0
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.4.3
      - multiprocess==0.70.16
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - ninja==1.11.1.3
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-ml-py==12.570.86
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - open-clip-torch==2.24.0
      - opencv-python==4.9.0.80
      - orjson==3.10.15
      - packaging==24.2
      - pandas==2.2.3
      - parso==0.8.4
      - pastel==0.2.1
      - pexpect==4.9.0
      - pfzy==0.3.4
      - pillow==10.2.0
      - platformdirs==4.3.7
      - pluggy==1.5.0
      - poethepoet==0.10.0
      - pot==0.9.5
      - prompt-toolkit==3.0.51
      - propcache==0.3.1
      - protobuf==6.30.2
      - psutil==6.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyarrow==19.0.1
      - pydantic==2.10.5
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pygments==2.19.1
      - pyparsing==3.2.1
      - pytest==8.3.5
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytorch-lightning==2.5.1.post0
      - pytz==2024.2
      - pyyaml==6.0.2
      - pyzmq==26.4.0
      - qwen-vl-utils==0.0.11
      - regex==2024.11.6
      - requests==2.32.3
      - rich==13.9.4
      - ruff==0.9.2
      - safetensors==0.4.3
      - scikit-image==0.25.0
      - scikit-learn==1.6.1
      - scipy==1.15.1
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - shtab==1.7.2
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.7
      - stable-diffusion-application==0.1
      - stack-data==0.6.3
      - starlette==0.41.3
      - sympy==1.13.1
      - tabulate==0.9.0
      - tb-nightly==2.20.0a20250428
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.0.1
      - threadpoolctl==3.6.0
      - tifffile==2025.1.10
      - timm==1.0.15
      - tokenizers==0.21.1
      - tomli==2.2.1
      - tomlkit==0.12.0
      - torch==2.6.0
      - torchao==0.10.0
      - torchaudio==2.5.1+cu124
      - torchcde==0.2.5
      - torchcfm==1.0.7
      - torchdiffeq==0.2.5
      - torchdyn==1.0.6
      - torchmetrics==1.7.1
      - torchsde==0.2.6
      - torchvision==0.21.0
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - trampoline==0.1.2
      - transformers==4.49.0
      - triton==3.2.0
      - typeguard==4.4.2
      - typer==0.15.1
      - typing-extensions==4.13.2
      - tyro==0.7.3
      - tzdata==2024.2
      - urllib3==2.3.0
      - uvicorn==0.34.0
      - wadler-lindig==0.1.5
      - wcwidth==0.2.13
      - websockets==12.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - xxhash==3.5.0
      - yapf==0.43.0
      - yarl==1.20.0
      - zipp==3.21.0
